app:
  jwt:
    secret-key: ${UR_JWT_SECRET_KEY:default-secret-key}
    expiration-time-ms: ${UR_JWT_EXPIRATION_TIME_MS:7200000}

spring:
  application:
    name: usersrole
  datasource:
    url: ${UR_PG_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jdw}
    username: ${UR_PG_USERNAME:default_user}
    password: ${UR_PG_PASSWORD:default_password}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: URPGPool
      connection-test-query: 'SELECT 1'
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 300000
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      leak-detection-threshold: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
