name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - if: ${{ github.event_name == 'pull_request' }}
        run: git branch --track main origin/main
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci
      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
      - if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "jdw-bot"
          npx nx affected -t version
          git push -u origin develop
