name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 300000
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Setup Base and SHAs for 'nx affected'
        uses: nrwl/nx-set-shas@v4
      - if: ${{ github.event_name == 'pull_request' }}
        name: Setup Main Branch Tracking
        run: git branch --track main origin/main
      - name: Run Format Check
        run: npx nx-cloud record -- nx format:check
      - name: Run Linting, Unit, Component, E2E, & Build Tests
        run: npx nx affected -t lint test build component-test e2e-ci
      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - if: ${{ github.event_name != 'pull_request' }}
        name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
      - if: ${{ github.event_name != 'pull_request' }}
        name: Run Version Upgrades
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          npx nx affected -t version --parallel=1
          git checkout -b develop && git push origin develop
