name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 300000
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - name: Enable NX Cloud Distribution
      #   run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
      - name: Install Dependencies
        run: npm ci
      - name: Setup Base and SHAs for 'nx affected'
        uses: nrwl/nx-set-shas@v4
      - if: ${{ github.event_name == 'pull_request' }}
        name: Setup Main Branch Tracking
        run: git branch --track main origin/main
      - name: Run Format Check
        run: npx nx-cloud record -- nx format:check
      - name: Run Linting, Unit, Component, & E2E Tests
        run: npx nx affected -t lint test component-test --skip-nx-cache
      - name: Run E2E Tests
        run: npx nx affected -t e2e --parallel=1
      - name: Run Build
        run: npx nx affected -t build
      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - if: ${{ github.event_name != 'pull_request' }}
        name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
      - if: ${{ github.event_name != 'pull_request' }}
        name: Run Version Upgrades
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          docker buildx create --use --name mybuilder --driver docker-container
          npx nx affected -t version --parallel=1
          git fetch origin develop
          git checkout develop
          git pull origin main --rebase
          git push --force-with-lease origin develop
